### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [Sabotnik/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Sabotnik** [comment]
Added viewport meta tag for bootstrap 3 via CSS-Bootstrap page http://getbootstrap.com/css/

Definitely looks better on mobile now, thanks Marco!

**Comment by MarcoMorawec** [comment]
:+1: @Sabotnik 

Great work - make sure you close the issue now that you're done with it :)
